"""add email column

Revision ID: 87012103c947
Revises: 8be51d441b40
Create Date: 2026-05-18 19:55:03.446927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87012103c947'
down_revision = '8be51d441b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
